---
title: "Land use land cover change due to green extractivism in Mozambique"
author: "Emilinah Namaganda"
date: "2022-11-01"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent
printing of the R code that generated the plot.

## Loading the necessary libraries

```{r}
library(sf) 
library(lintr) 
library(rpart) 
library(dismo) 
library(ggplot2)
library(reshape2)
library(randomForest)
library(RStoolbox)
library(caret)
library(e1071)
library(rgdal)
library(terra)
```

```{r}
# regularly remove temporary files

tmpFiles(current=TRUE, orphan=TRUE, old=TRUE, remove=F)

```


## Preprocessing Twigg (Balama), GK (Ancuabe) and Total (Palma) images

```{r}
# loading relevant image bands -----------
# TODO reorganise to start with ancb (not ancbe) and end with Plma
# TODO change ancuabe abbreviation from ancbe to ancb
# TODO start with the study areas and then input the bands close to the qa bands

studyareas_bands17 <- function(folders_images) {
  bands_all      <- list.files(folders_images,
                               recursive = T,
                               pattern = glob2rx("*B*"), 
                               full.names = TRUE)
  bands_17       <- bands_all[grep("B10", bands_all, invert = TRUE)]
  bands_list     <- list(bands_17[grep("2021.*165069", bands_17)],
                         bands_17[grep("2015.*165069", bands_17)],
                         bands_17[grep("2020.*165067", bands_17)],
                         bands_17[grep("2020.*164068", bands_17)],
                         bands_17[grep("2015.*165067", bands_17)],
                         bands_17[grep("2015.*164068", bands_17)],
                         bands_17[grep("2020.*165069", bands_17)],
                         bands_17[grep("2020.*164069", bands_17)],
                         bands_17[grep("2015.*165069", bands_17)],
                         bands_17[grep("2015.*164069", bands_17)])
  names(bands_list) <- (c("blma2021_b17",
                         "blma2015_b17",
                         "plma2020A_b17",
                         "plma2020B_b17",
                         "plma2015A_b17",
                         "plma2015B_b17",
                         "ancb2020A_b17",
                         "ancb2020B_b17",
                         "ancb2015A_b17",
                         "ancb2015B_b17"))
  bands          <- lapply(bands_list, rast)
  return(bands)
}
sa_bands <- studyareas_bands17("~/data/raw/images")
sa_bands


# removing cloud cover pixels, re-projecting to correct 
# coordinate reference system (CRS), cropping to area of interest

moz_crs    <- "+init=EPSG:32737"

# administrative posts where the mines and surrounding PACs are found

study_areasPosts <- function(mine_areas) {
  study_Posts <- list.files(mine_areas, 
                            pattern = "\\.shp$", 
                            full.names = TRUE)
  blmapost        <- vect(study_Posts[2])
  plmapost        <- vect(study_Posts[3])
  ancbpost        <- vect(study_Posts[1])
  return(list("blmapost" = blmapost, 
              "plmapost" = plmapost, 
              "ancbpost" = ancbpost))
}
sa_posts <- study_areasPosts("~/data/raw/mines/admposts")


# rectangles including mines and surrounding PACs
study_areas <- function(mine_areas) {
  study_areas <- list.files(mine_areas, 
                            pattern = "\\.shp$", 
                            full.names = TRUE)
  blma        <- vect(study_areas[2])
  plma        <- vect(study_areas[3])
  ancb        <- vect(study_areas[1])
  return(list("blma" = blma, 
              "plma" = plma, 
              "ancb" = ancb))
}
sa <- study_areas("~/data/raw/mines/stdyareas")


# totalAoi    <- crop(plma, total_bufSV) # created an extra AOI to 
# eliminate the ocean from analysis #TODO


study_mines <- function(mine_areas) {
  mines <- list.files(mine_areas, 
                      pattern = "\\.shp$", 
                      full.names = TRUE)
  twigg <- st_read(mines[3], 
                   query = "SELECT Mine FROM \"twigg\" WHERE FID = 0")
  total <- st_read(mines[2], 
                   query = "SELECT Name FROM \"total\" WHERE FID = 0")
  gk    <- st_read(mines[1], 
                   query = "SELECT Mine FROM \"gk\" WHERE FID = 0")
  return(list("twigg" = twigg, 
              "total" = total, 
              "gk" = gk))
}
mines <- study_mines("~/data/raw/mines/mines")


study_pacs <- function(mine_areas) {
  PACs       <- list.files(mine_areas, 
                     pattern = "\\.shp$", 
                     full.names = TRUE)
  twigg_pacs <- st_read(PACs[3], 
                        query = "SELECT NomeN1 FROM \"twiggPACS\"")
  total_pacs <- st_read(PACs[2], 
                        query = "SELECT Settlement FROM \"totalPACS\"")
  gk_pacs    <- st_read(PACs[1], 
                     query = "SELECT Community FROM \"gkPACS\"")
  return(list("twigg_pacs" = twigg_pacs, 
              "total_pacs" = total_pacs, 
              "gk_pacs" = gk_pacs))
}
pacs <- study_pacs("~/data/raw/mines/pacs")


sa_qabands <- function(mine_areas) {
  qa_bands <- list.files(mine_areas,
                         recursive = T,
                         pattern = "\\PIXEL.TIF$",
                         full.names = TRUE)
  sa_qa    <- list(qa_bands[grep("2021", qa_bands)], 
                   qa_bands[grep("2015.*165069", qa_bands)],
                   qa_bands[grep("2020.*165067", qa_bands)],
                   qa_bands[grep("2020.*164068", qa_bands)],
                   qa_bands[grep("2015.*165067", qa_bands)],
                   qa_bands[grep("2015.*164068", qa_bands)],
                   qa_bands[grep("2020.*165069", qa_bands)],
                   qa_bands[grep("2020.*164069", qa_bands)],
                   qa_bands[grep("2015.*165069", qa_bands)],
                   qa_bands[grep("2015.*164069", qa_bands)])
  names(sa_qa)    <- list("blma2021_qa",
                          "blma2015_qa",
                          "plma2020A_qa",
                          "plma2020B_qa",
                          "plma2015A_qa",
                          "plma2015B_qa",
                          "ancbe2020A_qa",
                          "ancbe2020B_qa",
                          "ancbe2015A_qa",
                          "ancbe2015B_qa")
  sa_qarast <- lapply(sa_qa, rast)
  return(sa_qarast)
}
qa_bands <- sa_qabands("~/data/raw/images")


qa_bandsCAT <- function(qa) {
  qab            <- qa[[1]]
  activeCat(qab) <- 0
  return(qab)
}
qa_CAT <- lapply(qa_bands, qa_bandsCAT)


aoi_L8  <- function(QAband, bands17, aoi_post) {
  cloudmask     <- classify(QAband, rbind(c(21824, 21824), c(21952, 21952)),
                         others = NA)
  b17_clear     <- mask(bands17, cloudmask)
  b17_clearProj <- terra::project(b17_clear, moz_crs)
  aoi_crop      <- crop(b17_clearProj, aoi_post, snap = "near", mask = TRUE)
  aoi_cropmsk    <- mask(aoi_crop, aoi_post)
  return(aoi_cropmsk)
}

#TODO use if else and for loop for chunk below?

aois <- function(aoi_fun, qaband, bands17, aoi_post) {
  sa_aoi        <- list(
    "blma2021"  = aoi_fun(qaband[[1]], bands17[[1]], aoi_post[[1]]),
    "blma2015"  = aoi_fun(qaband[[2]], bands17[[2]], aoi_post[[1]]),
    "plma2020A" = aoi_fun(qaband[[3]], bands17[[3]], aoi_post[[2]]),
    "plma2020B" = aoi_fun(qaband[[4]], bands17[[4]], aoi_post[[2]]),
    "plma2015A" = aoi_fun(qaband[[5]], bands17[[5]], aoi_post[[2]]),
    "plma2015B" = aoi_fun(qaband[[6]], bands17[[6]], aoi_post[[2]]),
    "ancbe2020A" = aoi_fun(qaband[[7]], bands17[[7]], aoi_post[[3]]),
    "ancbe2020B" = aoi_fun(qaband[[8]], bands17[[8]], aoi_post[[3]]),
    "ancbe2015A" = aoi_fun(qaband[[9]], bands17[[9]], aoi_post[[3]]),
    "ancbe2015B" = aoi_fun(qaband[[10]], bands17[[10]], aoi_post[[3]]))
  AncbPlma2020_2015  <- list(
    "ancbe2020" = mosaic(sa_aoi$ancbe2020A, sa_aoi$ancbe2020B),
    "ancbe2015" = mosaic(sa_aoi$ancbe2015A, sa_aoi$ancbe2015B),
    "plma2020" = mosaic(sa_aoi$plma2020A, sa_aoi$plma2020B),
    "plma2015" = mosaic(sa_aoi$plma2015A, sa_aoi$plma2015B))
  saAOI_combined <- c(sa_aoi, AncbPlma2020_2015)
  saAOI          <- saAOI_combined[-c(3:10)]
  return(saAOI)
}
aois_clean <- aois(aoi_L8, qa_CAT, sa_bands, sa_posts)
#Warning message:
#[mosaic] rasters did not align and were resampled

aois_clean_bandnames <- function(aois_list) {
  bandlist <- aois_list
  for (i in 1:length(bandlist)) {
  names(bandlist[[i]][[1:7]]) <- gsub(pattern = ".*SR",
                                   replacement = names(bandlist[i]),
                                   names(bandlist[[i]][[1:7]]))
  }
  return(bandlist)
}
aois_final <- aois_clean_bandnames(aois_clean)
aois_final

```

## Classifying the images (Fri/Sun/Mon)

```{r}
# composites and indices exported to arcgis to create training samples. 
# couldn't find how to do that in R. Perhaps additional benefit of GEE is that
# it is more self-contained?

comp   <- function(bands17, x, y, z) {
  comps    <- c(bands17[[x]], bands17[[y]], bands17[[z]])
  return(comps)
}

aois_RGB <- function(bands17) {
  aois_comp <- list("blma2021_b543" = comp(bands17[[1]], 5, 4, 3),
                   "blma2015_b543" = comp(bands17[[2]], 5, 4, 3),
                   "blma2021_b654" = comp(bands17[[1]], 6, 5, 4),
                   "blma2015_b654" = comp(bands17[[2]], 6, 5, 4),
                   "ancbe2020_b543" = comp(bands17[[3]], 5, 4, 3),
                   "ancbe2015_b543" = comp(bands17[[4]], 5, 4, 3),
                   "ancbe2020_b654" = comp(bands17[[3]], 6, 5, 4),
                   "ancbe2015_b654" = comp(bands17[[4]], 6, 5, 4),
                   "plma2020_b543" = comp(bands17[[5]], 5, 4, 3),
                   "plma2015_b543" = comp(bands17[[6]], 5, 4, 3),
                   "plma2020_b654" = comp(bands17[[5]], 6, 5, 4),
                   "plma2015_b654" = comp(bands17[[6]], 6, 5, 4))
  aois_compnames <- paste0(names(aois_comp), ".tif")
  names(aois_comp) <- aois_compnames
  for (i in 1:length(aois_comp)) {
  aoisComp <- writeRaster(aois_comp[[i]],
                 file.path("~/results/output", 
                           names(aois_comp[i])),
                 overwrite=TRUE,
                 filetype="GTiff")
  }
  return(aoisComp)
}

aois_compst <- aois_RGB(aois_final)

indices <- function(bands17, x, y) {
  bandx <- bands17[[x]]
  bandy <- bands17[[y]]
  indices <- (bandx - bandy)/(bandx + bandy)
  return(indices)
}

ndvi_fun <- function(bands17) {
  ndvi <- list("blma2021_ndvi" = indices(bands17[[1]], 5, 4),
     "blma2015_ndvi" = indices(bands17[[2]], 5, 4),
     "ancb2020_ndvi" = indices(bands17[[3]], 5, 4),
     "ancb2015_ndvi" = indices(bands17[[4]], 5, 4),
     "plma2020_ndvi" = indices(bands17[[5]], 5, 4),
     "plma2015_ndvi" = indices(bands17[[6]], 5, 4))
  ndvinames <- paste0(names(ndvi), ".tif")
  names(ndvi) <- ndvinames
  for (i in 1:length(ndvi)) {
  writeRaster(ndvi[[i]],
                 file.path("~/results/output", names(ndvi[i])),
                 overwrite=TRUE,
                 filetype="GTiff")
  }
  return(ndvi)
}
aois_ndvi <- ndvi_fun(aois_final)


## model training
# Water removed as a class from the Palma training sample. 
# It was too small to meet the accuracy needs of the classification. 
# It is now classified as wetland

trains <- list(
  "blma2021_train" = vect("~/data/temp/training-samples/blma2021_train500V3.shp"),
  "blma2015_train" = vect("~/data/temp/training-samples/blma2015_train500V2.shp"),
  "ancb2020_train" = vect("~/data/temp/training-samples/ancb2020_train500.shp"),
  "ancb2015_train" = vect("~/data/temp/training-samples/ancb2015_train500.shp"),
  "plma2020_train" = vect("~/data/temp/training-samples/plma2020_train500Weq_4cls.shp"),
  "plma2015_train" = vect("~/data/temp/training-samples/plma2015_train500_4clsv2.shp"))


# create training sample points from training sites data
# create training model  
# spatSample: In order to assure regularity when requesting a regular sample, 
# the number of cells or points returned may not be exactly the same as the 
# size requested (documentation Terra).

samps <- function(train, image_aoi) {
                set.seed(555)
  Tsamps     <- spatSample(train, 1000, method = "regular")
                print(table(as.character(Tsamps$Classname)))
  sampsXY    <- as.matrix(geom(Tsamps)[,c('x','y')])
  sampsdf    <- extract(image_aoi[[3:6]], sampsXY)
  samps      <- data.frame(class = Tsamps$Classname, sampsdf)
  sampsGeo   <- cbind(samps, sampsXY)
  sampsGeoSF <- st_as_sf(sampsGeo, coords = c("x", "y"), crs = moz_crs)
  return(sampsGeoSF)
}

study_samps <- mapply(trains, aois_final, FUN = samps, SIMPLIFY = F)
names(study_samps) <- c("blma2021_samps",
                        "blma2015_samps",
                        "ancb2020_samps",
                        "ancb2015_samps",
                        "plma2020_samps",
                        "plma2015_samps")


# inspect the spectral profiles of the training samples

lulc_classes <- list(class_BlmaAncb = c("built & bare",
                                        "dense vegetation",
                                        "sparse vegetation",
                                        "water"),
                     class_Plma = c("built & bare",
                                    "dense vegetation",
                                    "sparse vegetation",
                                    "wetland",
                                    "water"))

lulc_cols <- list(cols_BlmaAncb = c('darkorange', 
                                    'darkgreen', 
                                    'green', 
                                    'deepskyblue'),
                  cols_Plma = c('darkorange', 
                                'darkgreen', 
                                'green', 
                                'lightcyan', 
                                'deepskyblue'))

sampsSP <- function(samps) {
  sampsSP             <- aggregate(st_drop_geometry(samps)[, -1], list(samps$class), mean)
  rownames(sampsSP)   <- sampsSP[, 1]
  sampsSP             <- sampsSP[, -1]
  names(sampsSP)[1:4] <- 1:4
  sampsSP             <- t(sampsSP)
  sampsSP             <- as.data.frame(sampsSP)
  sampsSP             <- cbind(bands = rownames(sampsSP), sampsSP)
  rownames(sampsSP)   <- NULL
  sampsSP             <- melt(sampsSP, id.vars = "bands", variable.name = "lulc")
  sampsSP$bands       <- as.numeric(sampsSP$bands)
  return(sampsSP)
}

allsampsSP <- lapply(study_samps, sampsSP)


#TODO use if else statements to prevent repetition? or other ggplot way

sampsSPgraph             <- list(
  "blma2021sp" = ggplot(allsampsSP[[1]], aes(bands, value)) +
    geom_line(aes(color = lulc), size = 1) +
    ggtitle("Spectral Profile Balama 2021") +
    labs(x = "Bands", y = "Reflectance") +
    scale_colour_manual("LULC", 
                    values = lulc_cols$cols_BlmaAncb,
                    labels = lulc_classes$class_BlmaAncb),
  "blma2015sp" = ggplot(allsampsSP[[2]], aes(bands, value)) +
    geom_line(aes(color = lulc), size = 1) +
    ggtitle("Spectral Profile Balama 2015") +
    labs(x = "Bands", y = "Reflectance") +
    scale_colour_manual("LULC", 
                    values = lulc_cols$cols_BlmaAncb,
                    labels = lulc_classes$class_BlmaAncb),
  "ancb2020sp" = ggplot(allsampsSP[[3]], aes(bands, value)) +
    geom_line(aes(color = lulc), size = 1) +
    ggtitle("Spectral Profile Ancuabe 2020") +
    labs(x = "Bands", y = "Reflectance") +
    scale_colour_manual("LULC", 
                    values = lulc_cols$cols_BlmaAncb,
                    labels = lulc_classes$class_BlmaAncb),
  "ancb2015sp" = ggplot(allsampsSP[[4]], aes(bands, value)) +
    geom_line(aes(color = lulc), size = 1) +
    ggtitle("Spectral Profile Ancuabe 2015") +
    labs(x = "Bands", y = "Reflectance") +
    scale_colour_manual("LULC", 
                    values = lulc_cols$cols_BlmaAncb,
                    labels = lulc_classes$class_BlmaAncb),
  "plma2020sp" = ggplot(allsampsSP[[5]], aes(bands, value)) +
    geom_line(aes(color = lulc), size = 1) +
    ggtitle("Spectral Profile Palma 2020") +
    labs(x = "Bands", y = "Reflectance") +
    scale_colour_manual("LULC", 
                    values = lulc_cols$cols_Plma,
                    labels = lulc_classes$class_Plma),
  "plma2015sp" = ggplot(allsampsSP[[6]], aes(bands, value)) +
    geom_line(aes(color = lulc), size = 1) +
    ggtitle("Spectral Profile Palma 2015") +
    labs(x = "Bands", y = "Reflectance") +
    scale_colour_manual("LULC", 
                    values = lulc_cols$cols_Plma,
                    labels = lulc_classes$class_Plma)) 


# classify image

B_class      <- superClass(plma2020[[4:6]], trainPlma20SF, responseCol = "class", model = "mlc", trainPartition = 0.7)
B_classdf    <- as.data.frame(B_class$map, xy = TRUE)
B_class

B_classbuf <- crop(B_class$map, total_buf)
B_classbuf <- mask(B_class$map, total_buf)
writeRaster(B_classbuf, file.path("~/results/output", "palma2020class.tif"),
            overwrite=TRUE, filetype="GTiff")
B_classbufdf    <- as.data.frame(B_classbuf, xy = TRUE)
B_classbufdf_nna <- na.omit(B_classbufdf)

# Warning message:
# Raster pixels are placed at uneven horizontal intervals and will be shifted. 
# Consider using geom_tile() instead.Check difference btn geomtile and geomraster

par(mfrow = c(1, 2))


ggplot() +
  geom_tile(data = B_classbufdf_nna, aes(x = x, y = y, fill = class_value)) +
  geom_sf(data = total, colour = "black", fill = NA, size = 1) +
  geom_sf(data = plmaPACS, fill = NA) +
  geom_sf_text(data = plmaPACS, aes(label = Settlement)) +
  labs(x = NULL, 
       y = NULL, 
       title = "Palma 2020 land use land cover") +
  scale_fill_manual("LULC",
                    na.translate = FALSE,
                    values = colp,
                    labels = clasp) +
  coord_sf(datum = st_crs(total))

ggplot() +
  geom_sf(data = aois_clean$blma2021$LC08_L2SP_165069_20210609_20210615_02_T1_SR_B1) + 
  geom_sf(data = mines$twigg) +
  geom_sf(data = pacs$twigg_pacs) +
  coord_sf()

# crop by concession area

B_classTotal <- terra::crop(B_classbuf, total)
B_classTotal <- terra::mask(B_classTotal, st_zm(total))


# RStoolbox - Palma 2015

trainPlma2015    <- spatSample(plma2015_train, size = 8000, method = "random")
table(as.character(trainPlma2015$Classname))
trainPlma2015xy  <- as.matrix(geom(trainPlma2015)[,c('x','y')])
trainPlma15        <- extract(plma2015[[4:6]], trainPlma2015xy)
trainPlma15df      <- data.frame(class = trainPlma2015$Classname, trainPlma15)
trainPlma15dfdf2     <- cbind(trainPlma15df, trainPlma2015xy)
trainPlma15SF       <- st_as_sf(trainPlma15dfdf2, coords = c("x", "y"), crs = moz_crs)

B_class15      <- superClass(plma2015[[4:6]], trainPlma15SF, responseCol = "class", model = "mlc", trainPartition = 0.7)
B_class15
B_classdf15    <- as.data.frame(B_class15$map, xy = TRUE)
B_class15buf <- crop(B_class15$map, total_buf)
B_class15buf <- mask(B_class15$map, total_buf)
writeRaster(B_class15buf, file.path("~/results/output", "palma2015class.tif"),
            overwrite=TRUE, filetype="GTiff")
B_class15bufdf    <- as.data.frame(B_class15buf, xy = TRUE)
B_class15bufdf_nna <- na.omit(B_class15bufdf)

ggplot() +
  geom_tile(data = B_class15bufdf_nna, aes(x = x, y = y, fill = class_value)) +
  geom_sf(data = total, colour = "black", fill = NA, size = 1) +
  geom_sf(data = plmaPACS, fill = NA) +
  geom_sf_text(data = plmaPACS, aes(label = Settlement)) +
  labs(x = NULL, 
       y = NULL, 
       title = "Palma 2015 land use land cover") +
  scale_fill_manual("LULC",
                    na.translate = FALSE,
                    values = colp,
                    labels = clasp) +
  coord_sf(datum = st_crs(total))

# crop by concession area

B_class15Total <- crop(B_class15buf, total)
B_class15Total <- terra::mask(B_class15Total, st_zm(total))


# balama

# Balma 2021

trainblma2021    <- spatSample(blma2021_train, 8000, method = "random")
table(as.character(trainblma2021$Classname))
trainblma2021xy  <- as.matrix(geom(trainblma2021)[,c('x','y')])
trainblma21      <- extract(blma2021[[3:6]], trainblma2021xy)
trainblma21df      <- data.frame(class = trainblma2021$Classname, trainblma21)
trainblma21df2     <- cbind(trainblma21df, trainblma2021xy)
trainblma21SF       <- st_as_sf(trainblma21df2, coords = c("x", "y"), crs = moz_crs)

Blma2021_class      <- superClass(blma2021[[4:6]], trainblma21SF, responseCol = "class", model = "mlc", trainPartition = 0.7)
Blma2021_classdf    <- as.data.frame(Blma2021_class$map, xy = TRUE)
Blma2021_class
Blma2021_classbuf <- crop(Blma2021_class$map, syrah_buf)
Blma2021_classbuf <- mask(Blma2021_class$map, syrah_buf)
writeRaster(Blma2021_classbuf, file.path("~/results/output", "Balama2021class.tif"),
            overwrite=TRUE, filetype="GTiff")
Blma2021_classbufdf    <- as.data.frame(Blma2021_classbuf, xy = TRUE)
Blma2021_classbufdf_nna <- na.omit(Blma2021_classbufdf)

ggplot() +
  geom_tile(data = Blma2021_classbufdf_nna, aes(x = x, y = y, fill = class_value)) +
  geom_sf(data = syrah, fill=NA, colour = "black", size = 1) +
  geom_sf(data = blmaPACS, fill = NA) +
  geom_sf_text(data = blmaPACS, aes(label = NomeN1)) +
  labs(x = NULL, 
       y = NULL, 
       title = "Balama 2021 land use land cover") +
  scale_fill_manual("LULC",
                    na.translate = FALSE,
                    values = colb,
                    labels = clasb) +
  coord_sf(datum = st_crs(syrah))

# crop by concession area

Blma2021_classSyrah <- crop(Blma2021_classbuf, syrah)
Blma2021_classSyrah <- mask(Blma2021_classSyrah, st_zm(syrah))

# Balma 2015

trainblma2015    <- spatSample(blma2015_train, 8000, method = "random")
table(as.character(trainblma2015$Classname))
trainblma2015xy  <- as.matrix(geom(trainblma2015)[,c('x','y')])
trainblma15      <- extract(blma2015[[3:6]], trainblma2015xy)
trainblma15df      <- data.frame(class = trainblma2015$Classname, trainblma15)
trainblma15df2     <- cbind(trainblma15df, trainblma2015xy)
trainblma15SF       <- st_as_sf(trainblma15df2, coords = c("x", "y"), crs = moz_crs)


Blma2015_class      <- superClass(blma2015[[4:6]], trainblma15SF, responseCol = "class", model = "mlc", trainPartition = 0.7)
Blma2015_classdf    <- as.data.frame(Blma2015_class$map, xy = TRUE)
Blma2015_class
Blma2015_classbuf <- crop(Blma2015_class$map, syrah_buf)
Blma2015_classbuf <- mask(Blma2015_class$map, syrah_buf)
writeRaster(Blma2015_classbuf, file.path("~/results/output", "Balama2015class.tif"),
            overwrite=TRUE, filetype="GTiff")
Blma2015_classbufdf    <- as.data.frame(Blma2015_classbuf, xy = TRUE)
Blma2015_classbufdf_nna <- na.omit(Blma2015_classbufdf)

ggplot() +
  geom_tile(data = Blma2015_classbufdf_nna, aes(x = x, y = y, fill = class_value)) +
  geom_sf(data = syrah, fill=NA, colour = "black", size = 1) +
  geom_sf(data = blmaPACS, fill = NA) +
  geom_sf_text(data = blmaPACS, aes(label = NomeN1)) +
  labs(x = NULL, 
       y = NULL, 
       title = "Balama 2015 land use land cover") +
  scale_fill_manual("LULC",
                    na.translate = FALSE,
                    values = colb,
                    labels = clasb) +
  coord_sf(datum = st_crs(syrah))

# crop by concession area

Blma2015_classSyrah <- crop(Blma2015_classbuf, syrah)
Blma2015_classSyrah <- mask(Blma2015_classSyrah, st_zm(syrah))


# Ancuabe 2020

trainancb2020    <- spatSample(ancb2020_train, 8000, method = "random")
table(as.character(trainancb2020$Classname))
trainancb2020xy  <- as.matrix(geom(trainancb2020)[,c('x','y')])
trainancb20      <- extract(ancb2020[[4:6]], trainancb2020xy)
trainancb20df      <- data.frame(class = trainancb2020$Classname, trainancb20)
trainancb20df2     <- cbind(trainancb20df, trainancb2020xy)
trainancb20SF       <- st_as_sf(trainancb20df2, coords = c("x", "y"), crs = moz_crs)


Ancb2020_class      <- superClass(ancb2020[[4:6]], trainancb20SF, responseCol = "class", model = "mlc", trainPartition = 0.7)
Ancb2020_classdf    <- as.data.frame(Ancb2020_class$map, xy = TRUE)
Ancb2020_class
Ancb2020_classbuf <- crop(Ancb2020_class$map, gk_buf)
Ancb2020_classbuf <- mask(Ancb2020_class$map, gk_buf)
writeRaster(Ancb2020_classbuf, file.path("~/results/output", "Ancuabe2020class.tif"),
            overwrite=TRUE, filetype="GTiff")
Ancb2020_classbufdf    <- as.data.frame(Ancb2020_classbuf, xy = TRUE)
Ancb2020_classbufdf_nna <- na.omit(Ancb2020_classbufdf)

ggplot() +
  geom_tile(data = Ancb2020_classbufdf_nna, aes(x = x, y = y, fill = class_value)) +
  geom_sf(data = gk, fill=NA, colour = "black", size = 1) +
  geom_sf(data = ancbPACS, fill = NA) +
  geom_sf_text(data = ancbPACS, aes(label = Community)) +
  labs(x = NULL, 
       y = NULL, 
       title = "Ancuabe 2020 land use land cover") +
  scale_fill_manual("LULC",
                    na.translate = FALSE,
                    values = colp,
                    labels = clasp) +
  coord_sf(datum = st_crs(gk))

# crop by concession area

Ancb2020_classgk <- crop(Ancb2020_classbuf, gk)
Ancb2020_classgk <- mask(Ancb2020_classgk, st_zm(gk))

# Ancuabe 2015

trainancb2015    <- spatSample(ancb2015_train, 8000, method = "random")
table(as.character(trainancb2015$Classname))
trainancb2015xy  <- as.matrix(geom(trainancb2015)[,c('x','y')])
trainancb15      <- extract(ancb2015[[4:6]], trainancb2015xy)
trainancb15df      <- data.frame(class = trainancb2015$Classname, trainancb15)
trainancb15df2     <- cbind(trainancb15df, trainancb2015xy)
trainancb15SF       <- st_as_sf(trainancb15df2, coords = c("x", "y"), crs = moz_crs)

Ancb2015_class      <- superClass(ancb2015[[4:6]], trainancb15SF, responseCol = "class", model = "mlc", trainPartition = 0.7)
Ancb2015_classdf    <- as.data.frame(Ancb2015_class$map, xy = TRUE)
Ancb2015_class
Ancb2015_classbuf <- crop(Ancb2015_class$map, gk_buf)
Ancb2015_classbuf <- mask(Ancb2015_class$map, gk_buf)
writeRaster(Ancb2015_classbuf, file.path("~/results/output", "Ancuabe2015class.tif"),
            overwrite=TRUE, filetype="GTiff")
Ancb2015_classbufdf    <- as.data.frame(Ancb2015_classbuf, xy = TRUE)
Ancb2015_classbufdf_nna <- na.omit(Ancb2015_classbufdf)

ggplot() +
  geom_tile(data = Ancb2015_classbufdf_nna, aes(x = x, y = y, fill = class_value)) +
  geom_sf(data = gk, fill=NA, colour = "black", size = 1) +
  geom_sf(data = ancbPACS, fill = NA) +
  geom_sf_text(data = ancbPACS, aes(label = Community)) +
  labs(x = NULL, 
       y = NULL, 
       title = "Ancuabe 2015 land use land cover") +
  scale_fill_manual("LULC",
                    na.translate = FALSE,
                    values = colb,
                    labels = clasb) +
  coord_sf(datum = st_crs(gk))

# crop by concession area

Ancb2015_classgk <- crop(Ancb2015_classbuf, gk)
Ancb2015_classgk <- mask(Ancb2015_classgk, st_zm(gk))

```

## change detection 

```{r}
# all the vegetation has a more or less similar ndvi values. Difference betwn
# ranges is quite small. It can all be considered sparse vegetation. The benefit
# of learning about landscape.

# Change maps
# Palma
# 2020 - 2015
plma20_15 <-  B_classbuf - B_class15buf
plot(plma20_08)
plma20_08 <- B_classbuf - B_class08buf

plot(blma2021_ndvi-blma2009_ndvi)

# Balama



# Ancuabe



#palma

freq(B_classbuf)*0.0009
freq(B_class15buf)*0.0009

freq(B_classTotal)*0.0009
freq(B_class15Total)*0.0009

# balama

freq(Blma2021_classbuf)*0.0009
freq(Blma2015_classbuf)*0.0009

freq(Blma2021_classSyrah)*0.0009
freq(Blma2015_classSyrah)*0.0009

# ancuabe

freq(Ancb2020_classbuf)*0.0009
freq(Ancb2015_classbuf)*0.0009

freq(Ancb2020_classgk)*0.0009
freq(Ancb2015_classgk)*0.0009

```

