---
title: "Land use land cover change due to green extractivism in Mozambique"
author: "Emilinah Namaganda"
date: "7/18/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading the necessary libraries

```{r }
library(sf) # vector data
library(lintr) #organize writing style
library(rpart) # train classification model
library(dismo) # model evaluation
library(ggplot2)
library(reshape2) #converting dataframe to long format for ggplot
library(randomForest)
library(RStoolbox)
library(caret)
library(e1071)
library(rgdal)
library(terra) # raster data

```

## Preprocessing Balama images

```{r}

# loading relevant image bands -----------


bands17 <- function(images) {
  bands17 <- list.files(images,
    pattern = glob2rx("*B*"),
    full.names = TRUE)
  bands17 <- rast(bands17[1:7])
  return(bands17)
}

blma2021_b17 <- bands17("~/data/raw/images/2021/0609")
blma2015_b17 <- bands17("~/data/raw/images/2015/0524")
blma2009_b17 <- bands17("~/data/raw/images/2009/0624")

plma2020A_b17 <- bands17("~/data/raw/images/2020/0521")
plma2020B_b17 <- bands17("~/data/raw/images/2020/0701")
plma2015A_b17 <- bands17("~/data/raw/images/2015/0609")
plma2015B_b17 <- bands17("~/data/raw/images/2015/0517")
plma2008A_b17 <- bands17("~/data/raw/images/2008/0520")
plma2008B_b17 <- bands17("~/data/raw/images/2008/0326")
plma2008B_b17

# removing cloud cover pixels, re-projecting to correct CRS, crop to AOI ------

moz_crs    <- "+init=EPSG:32737"
blma       <- st_read("~/data/raw/mines/blma.shp", query = "SELECT POSTO FROM \"blma\"")
syrah      <- st_read("~/data/raw/mines/syrah.shp",
  query = "SELECT Mine FROM \"syrah\" WHERE FID = 0")
syrah_buf  <- st_buffer(syrah, 9000)
syrah_bufSV <- vect(as(syrah_buf, "Spatial"))

total      <- st_read("~/data/raw/mines/total.shp",
  query = "SELECT Name FROM \"total\" WHERE FID = 0")
total_buf  <- st_buffer(total, 12000)
total_bufSV <- vect(as(total_buf, "Spatial"))
  
ggplot() +
  geom_sf(data = total_buf) + 
  geom_sf(data = total) +
  coord_sf()

col4 <- c('darkorange', 'darkgreen', 'green', 'deepskyblue')
col5 <- c('darkorange', 'darkgreen', 'green', 'deepskyblue', 'lightcyan')
clas4 <- c("built & bare", "dense vegetation", "sparse vegetation", "water")
clas5 <- c("built & bare", "dense vegetation", "sparse vegetation", "water", "wetland")

blma2021_qa            <- rast(
  "~/data/raw/images/2021/0609/LC08_L2SP_165069_20210609_20210615_02_T1_QA_PIXEL.TIF") 
# check how to decode qa band in QGIS (open source).
activeCat(blma2021_qa) <- 0
plot(blma2021_qa)

blma2015_qa            <- rast(
  "~/data/raw/images/2015/0524/LC08_L2SP_165069_20150524_20200909_02_T1_QA_PIXEL.TIF") 
activeCat(blma2015_qa) <- 0

blma2009_qa            <- rast(
  "~/data/raw/images/2009/0624/LT05_L2SP_165069_20090624_20200827_02_T1_QA_PIXEL.TIF") 
activeCat(blma2009_qa) <- 0
plot(blma2009_qa)

plma2020A_qa            <- rast(
  "~/data/raw/images/2020/0521/LC08_L2SP_165067_20200521_20200820_02_T1_QA_PIXEL.TIF") 
# check how to decode qa band in QGIS (open source).
activeCat(plma2020A_qa) <- 0
plot(plma2020A_qa)
plma2020B_qa            <- rast(
  "~/data/raw/images/2020/0701/LC08_L2SP_164068_20200701_20200913_02_T1_QA_PIXEL.TIF") 
# check how to decode qa band in QGIS (open source).
activeCat(plma2020B_qa) <- 0
plot(plma2020B_qa)

plma2015A_qa            <- rast(
  "~/data/raw/images/2015/0609/LC08_L2SP_165067_20150609_20200909_02_T1_QA_PIXEL.TIF") 
activeCat(plma2015A_qa) <- 0
plot(plma2015A_qa)
plma2015B_qa            <- rast(
  "~/data/raw/images/2015/0517/LC08_L2SP_164068_20150517_20200909_02_T1_QA_PIXEL.TIF") 
activeCat(plma2015B_qa) <- 0
plot(plma2015B_qa)

plma2008A_qa            <- rast(
  "~/data/raw/images/2008/0520/LT05_L2SP_165067_20080520_20200829_02_T1_QA_PIXEL.TIF") 
activeCat(plma2008A_qa) <- 0
plot(plma2008A_qa)
plma2008B_qa            <- rast(
  "~/data/raw/images/2008/0326/LT05_L2SP_164068_20080326_20200829_02_T1_QA_PIXEL.TIF") 
activeCat(plma2008B_qa) <- 0
plot(plma2008B_qa)

aoi_L8             <- function(QAband, bands17, aoi_SF, aoi_vect) {
  cloudmask     <- classify(QAband, rbind(c(21824, 21824), c(21952, 21952)),
                         others = NA) # TODO open issue in Terra others=NULL doesn't work anymore
  b17_clear     <- mask(bands17, cloudmask)
  b17_clearProj <- project(b17_clear, moz_crs)
  aoi_crop      <- crop(b17_clearProj, aoi_SF, snap = "near", mask = TRUE)
  aoi_cropSV    <- mask(aoi_crop, aoi_vect)
  return(aoi_cropSV)
}

aoi_L5          <- function(QAband, bands17, aoi_SF, aoi_vect) {
  cloudmask     <- classify(QAband, rbind(c(5440, 5440), c(5504, 5504)),
                         others = NA)
  b17_clear     <- mask(bands17, cloudmask)
  b17_clearProj <- project(b17_clear, moz_crs)
  aoi_crop      <- crop(b17_clearProj, aoi_SF, snap = "near", mask = TRUE)
  aoi_cropSV    <- mask(aoi_crop, aoi_vect)
  return(aoi_cropSV)
}

blma2021        <- aoi_L8(blma2021_qa, blma2021_b17, syrah_buf, syrah_bufSV)
names(blma2021) <- gsub(
  pattern = "LC08_L2SP_165069_20210609_20210615_02_T1_SR",
  replacement = "blma2021",
  names(blma2021))

blma2015        <- aoi_L8(blma2015_qa, blma2015_b17, syrah_buf, syrah_bufSV)
names(blma2015) <- gsub(
  pattern = "LC08_L2SP_165069_20150524_20200909_02_T1_SR",
  replacement = "blma2015",
  names(blma2015))

blma2009        <- aoi_L5(blma2009_qa, blma2009_b17, syrah_buf, syrah_bufSV)
names(blma2009) <- gsub(
  pattern = "LT05_L2SP_165069_20090624_20200827_02_T1_SR",
  replacement = "blma2009",
  names(blma2009))
names(blma2009) <- gsub(
  pattern = "LT05_L2SP_165069_20090624_20200827_02_T1_ST",
  replacement = "blma2009",
  names(blma2009))

plma2020A        <- aoi_L8(plma2020A_qa, plma2020A_b17, total_buf, total_bufSV)
names(plma2020A) <- gsub(
  pattern = "LC08_L2SP_165067_20200521_20200820_02_T1_SR",
  replacement = "plma2020A",
  names(plma2020A))
plma2020B        <- aoi_L8(plma2020B_qa, plma2020B_b17, total_buf, total_bufSV)
names(plma2020B) <- gsub(
  pattern = "LC08_L2SP_164068_20200701_20200913_02_T1_SR",
  replacement = "plma2020B",
  names(plma2020B))
plma2020 <- mosaic(plma2020A, plma2020B)

plma2015A        <- aoi_L8(plma2015A_qa, plma2015A_b17, total_buf, total_bufSV)
names(plma2015A) <- gsub(
  pattern = "LC08_L2SP_165067_20150609_20200909_02_T1_SR",
  replacement = "plma2015A",
  names(plma2015A))
plma2015B        <- aoi_L8(plma2015B_qa, plma2015B_b17, total_buf, total_bufSV)
names(plma2015B) <- gsub(
  pattern = "LC08_L2SP_164068_20150517_20200909_02_T1_SR",
  replacement = "plma2015B",
  names(plma2015B))
plma2015 <- mosaic(plma2015A, plma2015B)

plma2008A        <- aoi_L5(plma2008A_qa, plma2008A_b17, total_buf, total_bufSV)
names(plma2008A) <- gsub(
  pattern = "LT05_L2SP_165067_20080520_20200829_02_T1_SR",
  replacement = "plma2008A",
  names(plma2008A))
names(plma2008A) <- gsub(
  pattern = "LT05_L2SP_165067_20080520_20200829_02_T1_ST",
  replacement = "plma2008A",
  names(plma2008A))
plma2008B        <- aoi_L5(plma2008B_qa, plma2008B_b17, total_buf, total_bufSV)
names(plma2008B) <- gsub(
  pattern = "LT05_L2SP_164068_20080326_20200829_02_T1_SR",
  replacement = "plma2008B",
  names(plma2008B))
names(plma2008B) <- gsub(
  pattern = "LT05_L2SP_164068_20080326_20200829_02_T1_ST",
  replacement = "plma2008B",
  names(plma2008B))
plma2008 <- mosaic(plma2008A, plma2008B)

```

## Classifying Balama 2021 image

```{r}

# composites and indices exported to arcgis to create training samples. 
# couldn't find how to do that in R. Perhaps additional benefit of GEE is that
# it is more self-contained?

par(mfrow = c(1, 2))

comps   <- function(bands17, x, y, z) {
  comps <-c(bands17[[x]], bands17[[y]], bands17[[z]])
  return(comps)
}

blma2021_b543 <- comps(blma2021, 5, 4, 3)
writeRaster(blma2021_b543, file.path("~/results/output", "blma2021_b543.tif"),
            overwrite=TRUE, filetype="GTiff")
blma2015_b543 <- comps(blma2015, 5, 4, 3)
writeRaster(blma2015_b543, file.path("~/results/output", "blma2015_b543.tif"),
            overwrite=TRUE, filetype="GTiff")
blma2009_b432 <- comps(blma2009, 4, 3, 2)
writeRaster(blma2009_b432, file.path("~/results/output", "blma2009_b432.tif"),
            overwrite=TRUE, filetype="GTiff")

blma2021_b654 <- comps(blma2021, 6, 5, 4)
writeRaster(blma2021_b654, file.path("~/results/output", "blma2021_b654.tif"),
            overwrite=TRUE, filetype="GTiff")
blma2015_b654 <- comps(blma2015, 6, 5, 4)
writeRaster(blma2015_b654, file.path("~/results/output", "blma2015_b654.tif"),
            overwrite=TRUE, filetype="GTiff")
blma2009_b543 <- comps(blma2009, 5, 4, 3)
writeRaster(blma2009_b543, file.path("~/results/output", "blma2009_b543.tif"),
            overwrite=TRUE, filetype="GTiff")

plma2020_b543 <- comps(plma2020, 5, 4, 3)
writeRaster(plma2020_b543, file.path("~/results/output", "plma2020_b543.tif"),
            overwrite=TRUE, filetype="GTiff")
plma2015_b543 <- comps(plma2015, 5, 4, 3)
writeRaster(plma2015_b543, file.path("~/results/output", "plma2015_b543.tif"),
            overwrite=TRUE, filetype="GTiff")
plma2008_b432 <- comps(plma2008, 4, 3, 2)
writeRaster(plma2008_b432, file.path("~/results/output", "plma2008_b432.tif"),
            overwrite=TRUE, filetype="GTiff")

plma2020_b654 <- comps(plma2020, 6, 5, 4)
writeRaster(plma2020_b654, file.path("~/results/output", "plma2020_b654.tif"),
            overwrite=TRUE, filetype="GTiff")
plma2015_b654 <- comps(plma2015, 6, 5, 4)
writeRaster(plma2015_b654, file.path("~/results/output", "plma2015_b654.tif"),
            overwrite=TRUE, filetype="GTiff")
plma2008_b543 <- comps(plma2008, 5, 4, 3)
writeRaster(plma2008_b543, file.path("~/results/output", "plma2008_b543.tif"),
            overwrite=TRUE, filetype="GTiff")

plotRGB(plma2008_b432, r = 1, g = 2, b = 3, stretch = "lin")
plot(total, add = TRUE, col=NA)


indices <- function(bands17, x, y) {
  bandx <- bands17[[x]]
  bandy <- bands17[[y]]
  indices <- (bandx - bandy)/(bandx + bandy)
  return(indices)
}


blma2021_ndvi <- indices(blma2021, 5, 4)
writeRaster(blma2021_ndvi, file.path("~/results/output", "blma2021_ndvi.tif"),
            overwrite=TRUE, filetype="GTiff")
blma2015_ndvi <- indices(blma2015, 5, 4)
writeRaster(blma2015_ndvi, file.path("~/results/output", "blma2015_ndvi.tif"),
            overwrite=TRUE, filetype="GTiff")
blma2009_ndvi <- indices(blma2009, 4, 3)
writeRaster(blma2009_ndvi, file.path("~/results/output", "blma2009_ndvi.tif"),
            overwrite=TRUE, filetype="GTiff")

blma2021_ndbi <- indices(blma2021, 6, 5)
writeRaster(blma2021_ndbi, file.path("~/results/output", "blma2021_ndbi.tif"),
            overwrite=TRUE, filetype="GTiff")
blma2015_ndbi <- indices(blma2015, 6, 5)
writeRaster(blma2015_ndbi, file.path("~/results/output", "blma2015_ndbi.tif"),
            overwrite=TRUE, filetype="GTiff")
blma2009_ndbi <- indices(blma2009, 5, 4)
writeRaster(blma2009_ndbi, file.path("~/results/output", "blma2009_ndbi.tif"),
            overwrite=TRUE, filetype="GTiff")

blma2021_mndwi <- indices(blma2021, 3, 6)
writeRaster(blma2021_mndwi, file.path("~/results/output", "blma2021_mndwi.tif"),
            overwrite=TRUE, filetype="GTiff")
blma2015_mndwi <- indices(blma2015, 3, 6)
writeRaster(blma2015_mndwi, file.path("~/results/output", "blma2015_mndwi.tif"),
            overwrite=TRUE, filetype="GTiff")
blma2009_mndwi <- indices(blma2009, 2, 5)
writeRaster(blma2009_mndwi, file.path("~/results/output", "blma2009_mndwi.tif"),
            overwrite=TRUE, filetype="GTiff")

plma2020_ndvi <- indices(plma2020, 5, 4)
writeRaster(plma2020_ndvi, file.path("~/results/output", "plma2020_ndvi.tif"),
            overwrite=TRUE, filetype="GTiff")
plma2015_ndvi <- indices(plma2015, 5, 4)
writeRaster(plma2015_ndvi, file.path("~/results/output", "plma2015_ndvi.tif"),
            overwrite=TRUE, filetype="GTiff")
plma2008_ndvi <- indices(plma2008, 4, 3)
writeRaster(plma2008_ndvi, file.path("~/results/output", "plma2008_ndvi.tif"),
            overwrite=TRUE, filetype="GTiff")

plma2020_ndbi <- indices(plma2020, 6, 5)
writeRaster(plma2020_ndbi, file.path("~/results/output", "plma2020_ndbi.tif"),
            overwrite=TRUE, filetype="GTiff")
plma2015_ndbi <- indices(plma2015, 6, 5)
writeRaster(plma2015_ndbi, file.path("~/results/output", "plma2015_ndbi.tif"),
            overwrite=TRUE, filetype="GTiff")
plma2008_ndbi <- indices(plma2008, 5, 4)
writeRaster(plma2008_ndbi, file.path("~/results/output", "plma2008_ndbi.tif"),
            overwrite=TRUE, filetype="GTiff")

plma2020_mndwi <- indices(plma2020, 3, 6)
writeRaster(plma2020_mndwi, file.path("~/results/output", "plma2020_mndwi.tif"),
            overwrite=TRUE, filetype="GTiff")
plma2015_mndwi <- indices(plma2015, 3, 6)
writeRaster(plma2015_mndwi, file.path("~/results/output", "plma2015_mndwi.tif"),
            overwrite=TRUE, filetype="GTiff")
plma2008_mndwi <- indices(plma2008, 2, 5)
writeRaster(plma2008_mndwi, file.path("~/results/output", "plma2008_mndwi.tif"),
            overwrite=TRUE, filetype="GTiff")

## model training

blma2021_train <- vect("~/data/temp/training-samples/blma2021_train500V2.shp")
blma2015_train <- vect("~/data/temp/training-samples/blma2015_train500.shp")
blma2009_train <- vect("~/data/temp/training-samples/blma2009_train500.shp")

plma2020_train <- vect("~/data/temp/training-samples/plma2020_train500.shp")
plma2015_train <- vect("~/data/temp/training-samples/plma2015_train500.shp")
plma2008_train <- vect("~/data/temp/training-samples/plma2008_train500.shp")

plot(blma2009_train)

# create training samples from ground truth training sites data

samps <- function(train, aoi) {
  Tsamps  <- spatSample(train, 4500, method = "random")
  sampsXY <- as.matrix(geom(Tsamps)[,c('x','y')])
  sampsdf <- extract(aoi, sampsXY)
  samps   <- data.frame(class = Tsamps$Classname, sampsdf)
  return(samps)
}

blma2021_samps     <- samps(blma2021_train, blma2021[[3:6]])
str(blma2021_samps)
blma2021_sampsDist <- table(as.character(blma2021_samps$class))
blma2021_sampsDist
write.table(blma2021_sampsDist, 
            file.path("~/results/output", "blma2021_sampsDist.csv"))

blma2015_samps     <- samps(blma2015_train, blma2015[[3:6]])
str(blma2015_samps)
blma2015_sampsDist <- table(as.character(blma2015_samps$class))
blma2015_sampsDist
write.table(blma2015_sampsDist, 
            file.path("~/results/output", "blma2015_sampsDist.csv"))

blma2009_samps     <- samps(blma2009_train, blma2009[[2:5]])
str(blma2009_samps)
blma2009_sampsDist <- table(as.character(blma2009_samps$class))
blma2009_sampsDist
write.table(blma2009_sampsDist, 
            file.path("~/results/output", "blma2009_sampsDist.csv"))


plma2020_samps     <- samps(plma2020_train, plma2020[[3:6]])
str(plma2020_samps)
plma2020_sampsDist <- table(as.character(plma2020_samps$class))
plma2020_sampsDist
write.table(plma2020_sampsDist, 
            file.path("~/results/output", "plma2020_sampsDist.csv"))

plma2015_samps     <- samps(plma2015_train, plma2015[[3:6]])
str(plma2015_samps)
plma2015_sampsDist <- table(as.character(plma2015_samps$class))
plma2015_sampsDist
write.table(plma2015_sampsDist, 
            file.path("~/results/output", "plma2015_sampsDist.csv"))

plma2008_samps     <- samps(plma2008_train, plma2008[[2:5]])
str(plma2008_samps)
plma2008_sampsDist <- table(as.character(plma2008_samps$class))
plma2008_sampsDist
write.table(plma2008_sampsDist, 
            file.path("~/results/output", "plma2008_sampsDist.csv"))

# inspect the spectral profiles of the training samples

sampsSP <- function(samps) {
  sampsSP             <- aggregate(samps[, -1], list(samps$class), mean)
  rownames(sampsSP)   <- sampsSP[, 1]
  sampsSP             <- sampsSP[, -1]
  names(sampsSP)[1:4] <- 1:4
  sampsSP             <- t(sampsSP)
  sampsSP             <- as.data.frame(sampsSP)
  sampsSP             <- cbind(bands = rownames(sampsSP), sampsSP)
  rownames(sampsSP)   <- NULL
  sampsSP             <- melt(sampsSP, id.vars = "bands", variable.name = "lulc")
  sampsSP$bands       <- as.numeric(sampsSP$bands)
  sampsSP             <- ggplot(sampsSP, aes(bands, value)) +
    geom_line(aes(color = lulc), size = 1) +
    ggtitle("Spectral Profiles") +
    labs(x = "Bands", y = "Reflectance") +
    scale_colour_manual("LULC", 
                    values = col4,
                    labels = clas4)
  return(sampsSP)
}
sampsSP(blma2021_samps)
sampsSP(blma2015_samps)
sampsSP(blma2009_samps)

sampsSP(plma2020_samps)
sampsSP(plma2015_samps)
sampsSP(plma2008_samps)

# create training model and classify image

# random forest

lulc <- function(samps, aoi) {
  model      <- rpart(as.factor(class)~., data = samps, 
                         method = 'class', minsplit = 5)
  classified <- predict(aoi, model, na.rm = TRUE)
  lulc       <- which.max(classified)
  return(lulc)
}


blma2021_samps$class <- as.factor(blma2021_samps$class)
blma2021_model <- randomForest(class~., data = blma2021_samps, importance=TRUE, proximity=TRUE)
print(blma2021_model)
blma2021_lulc   <- predict(blma2021[[3:6]], blma2021_model, na.rm = TRUE)

blma2009_lulc           <- lulc(blma2009_samps, blma2009[[2:5]]) 
# plotting classified image

blma2021_lulcdf         <- blma2021_lulc
lulc_df                 <- data.frame(id = 1:4, lulc = clas4)
levels(blma2021_lulcdf) <- lulc_df
blma2021_lulcdf         <- as.data.frame(blma2021_lulcdf, xy = TRUE)

ggplot() +
  geom_raster(data = blma2009_lulcdf, aes(x = x, y = y, fill = lulc)) +
  geom_sf(data = syrah, fill = NA) +
  labs(x = NULL, 
       y = NULL, 
       title = "Balama 2015 land use land cover") +
  scale_fill_manual("LULC", 
                    values = col4,
                    labels = clas4) +
  coord_sf()


blma2015_lulcdf         <- blma2015_lulc
lulc_df                 <- data.frame(id = 1:4, lulc = clas4)
levels(blma2015_lulcdf) <- lulc_df
blma2015_lulcdf         <- as.data.frame(blma2015_lulcdf, xy = TRUE)

ggplot() +
  geom_raster(data = blma2015_lulcdf, aes(x = x, y = y, fill = lulc)) +
  geom_sf(data = syrah, fill = NA) +
  labs(x = NULL, 
       y = NULL, 
       title = "Balama 2015 land use land cover") +
  scale_fill_manual("LULC", 
                    values = col4,
                    labels = clas4) +
  coord_sf()

blma2009_lulcdf         <- blma2009_lulc
lulc_df                 <- data.frame(id = 1:4, lulc = clas4)
levels(blma2009_lulcdf) <- lulc_df
blma2009_lulcdf         <- as.data.frame(blma2009_lulcdf, xy = TRUE)

ggplot() +
  geom_raster(data = blma2009_lulcdf, aes(x = x, y = y, fill = lulc)) +
  geom_sf(data = syrah, fill = NA) +
  labs(x = NULL, 
       y = NULL, 
       title = "Balama 2009 land use land cover") +
  scale_fill_manual("LULC", 
                    values = col4,
                    labels = clas4) +
  coord_sf()


# model evaluation

blma2021_sampGrps   <- kfold(blma2021_samps, k = 5, by = blma2021_samps$class)
table(blma2021_sampGrps)
blma2021Accuracies <- list()

blma2015_sampGrps   <- kfold(blma2015_samps, k = 5, by = blma2015_samps$class)
table(blma2015_sampGrps)
blma2015Accuracies <- list()

blma2009_sampGrps   <- kfold(blma2009_samps, k = 5, by = blma2009_samps$class)
table(blma2009_sampGrps)
blma2009Accuracies <- list()

for (k in 1:5) {
  blma2021Train      <- blma2021_samps[blma2021_sampGrps!= k, ]
  blma2021Test       <- blma2021_samps[blma2021_sampGrps == k, ]
  blma2021Model      <- rpart(as.factor(class)~., data=blma2021Train, method = 'class', minsplit = 5) # TODO check minsplit value.
  blma2021Classified <- predict(blma2021Model, blma2021Test, na.rm = TRUE) 
  blma2021Lulc       <- apply(blma2021Classified, 1, which.max)
  blma2021Accuracies[[k]] <- cbind(blma2021Test$class, as.integer(blma2021Lulc))
}
blma2021Accuracies

for (k in 1:5) {
  blma2015Train      <- blma2021_samps[blma2015_sampGrps!= k, ]
  blma2015Test       <- blma2021_samps[blma2015_sampGrps == k, ]
  blma2015Model      <- rpart(as.factor(class)~., data=blma2015Train, method = 'class', minsplit = 5) # TODO check minsplit value.
  blma2015Classified <- predict(blma2015Model, blma2015Test, na.rm = TRUE) 
  blma2015Lulc       <- apply(blma2015Classified, 1, which.max)
  blma2015Accuracies[[k]] <- cbind(blma2015Test$class, as.integer(blma2015Lulc))
}
blma2015Accuracies

for (k in 1:5) {
  blma2009Train      <- blma2009_samps[blma2009_sampGrps!= k, ]
  blma2009Test       <- blma2009_samps[blma2009_sampGrps == k, ]
  blma2009Model      <- rpart(as.factor(class)~., data=blma2009Train, method = 'class', minsplit = 5) # TODO check minsplit value.
  blma2009Classified <- predict(blma2009Model, blma2009Test, na.rm = TRUE) 
  blma2009Lulc       <- apply(blma2009Classified, 1, which.max)
  blma2009Accuracies[[k]] <- cbind(blma2009Test$class, as.integer(blma2009Lulc))
}
blma2009Accuracies

# lulc accuracy assessment

lulc_acc <- function(accuracies) {
  acctidy            <- do.call(rbind, accuracies)
  acctidy            <- data.frame(acctidy)
  colnames(acctidy)  <- c('observed', 'predicted')
  confmat            <- table(acctidy)
  colnames(confmat)  <- lulc_df$class
  samples            <- sum(confmat)
  samples_true       <- diag(confmat)
  overallAcc         <- sum(samples_true)/samples
  obsCases           <- apply(confmat, 1, sum)
  obsCases_true      <- obsCases/samples
  predCases          <- apply(confmat, 2, sum)
  predCases_true     <- predCases/samples
  expAcc             <- sum(obsCases_true*predCases_true)
  kappa              <- (overallAcc - expAcc)/(1 - expAcc)
  ProdAcc            <- samples_true/predCases
  UserAcc            <- samples_true/obsCases
  outAcc             <- data.frame(ProdAcc, UserAcc)
  lulc_acc           <- list(confmat, overallAcc, kappa, outAcc)
  return(lulc_acc)
}

blma2021_lulcAcc <- lulc_acc(blma2021Accuracies)
blma2021_lulcAcc

blma2015_lulcAcc <- lulc_acc(blma2015Accuracies)
blma2015_lulcAcc

blma2009_lulcAcc <- lulc_acc(blma2009Accuracies)
blma2009_lulcAcc

.
```

## change detection

```{r}

freq(blma2009_lulc)*0.0009
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent
printing of the R code that generated the plot.
